# Generated by Django 3.1.6 on 2021-05-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avail_listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='pay',
        ),
    ]
